services:
  nodejs:
    build:
      context: backend/
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    networks:
      - spotify-session-network
  nginx:
    build:
      context: ./
      dockerfile: server/Dockerfile
    ports:
      - 80:80
    networks:
      - spotify-session-network

networks:
  spotify-session-network:
    driver: bridge
