services:
  nginx:
    build:
      context: ./
      dockerfile: server/Dockerfile
    ports:
      - 80:80
    networks:
      - spotify-session-network

networks:
  spotify-session-network:
    driver: bridge
