services:
  node-server:
    build:
      context: backend/
      dockerfile: Dockerfile
    container_name: spotify-session-server
    env_file:
      - configs/server.env
      - backend/token.env
      - backend/client-token.env
    volumes:
       - ./backend/token.env:/usr/src/app/token.env
       - ./backend/client-token.env:/usr/src/app/client-token.env
    networks:
      - spotify-session-network
    depends_on:
      - mariadb
    entrypoint: ["./scripts/wait-for-it.sh", "mariadb", "3306", "npm", "start"]

  nginx:
    build:
      context: ./
      dockerfile: server/Dockerfile
    container_name: nginx-container
    ports:
      - 80:80
    networks:
      - spotify-session-network
    depends_on:
      - node-server
  
  mariadb:
    image: mariadb:10.5
    container_name: mariadb-container
    env_file:
      - configs/database.env
    volumes:
       - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - spotify-session-network

networks:
  spotify-session-network:
    driver: bridge
