server {
    listen 80;
    server_name 192.168.0.171 127.0.0.1;

    root /usr/share/nginx/html;

    location / {
        index index.html;
        try_files $uri $uri/ =404;
        add_header Cache-Control 'no-cache';
    }

    location /static {
        alias /usr/share/nginx/;
        add_header Cache-Control 'no-cache';
    }
}